language: node_js
  - "6"
dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - mkdir travis-phantomjs
  - wget https://github.com/ariya/phantomjs/archive/2.1.3.tar.gz -O $PWD/travis-phantomjs/phantomjs-2.1.3.tar.gz
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.3.tar.gz -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
script: 
  - phantomjs ./tests/phantomjsTest.js